### ISSUE TITLE
GetPriority Is Liable To Fail

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#129]
Key Error will be returned from getPriority for most items because their priority does not fall on the range on priorityEquivalent. This can be done by ensuring that new items will have a priority between 1-3 or by removing the priority dictionary entirely.

Note: at the time of writing getPriorty will not run, the line needs to be changed to 
return Item.priorityEquivalents[self.itemPriority] 

ClassName. is used to access the static elements of a class in Python.

**Comment by fallinbryan** [comment]
Setting default value in db for item priority to 1 now

**Comment by fallinbryan** [comment]
db modifications complete

**Comment by fallinbryan** [comment]
also modified all items with priority 0 to 1
