### ISSUE TITLE
Analytics Views

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#134]

**Comment by fallinbryan** [comment]
Blocked by #153

**Comment by fallinbryan** [comment]
Promoted to Epic as Issue will most likely require sub-tasks to complete.
Please xref this issue number (#134)  so that the show up on this feed

**Comment by fallinbryan** [comment]
Will need to manually change some date values in the database to test velocity curves

**Comment by Kroronos** [comment]
https://github.com/CEN3031-group16/GroupProject/pull/293
