### ISSUE TITLE
Backlog Manager View Does Not Update

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#166]
Backlog View does not update when updater detects change.  Only when clicking on File-Open-Project. Then the lists will update.  Developer Home updates.  How is the updater built for that? Do it like that.

**Comment by fallinbryan** [comment]
activeProject becomes a stale project when updater rebuilds all lists.
Packed updater function needs to re-point active project to newly built project object

**Comment by CEN3031-group16** [comment]
Pending approval of Pull Request #200
