### ISSUE TITLE
Item Manger View ~ Change Dialog Called by Add Item

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#168]
In Item Manger View, the add item dialog already implemented in Dialogs.py should be used.

The dialog is already there and works,  why not use it?

Maybe even recognize that when the fields are filled in on the view, if it is not an existing item, the add item button creates a new item as opposed to to calling a dialog.

UI needs consistency across views.

**Comment by Stevieberk** [comment]
Item Manager View Deleted
