### ISSUE TITLE
Assigned Item Status is not consistent with status equivalents

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#185]
When an item is assigned to a user, its status should automatically move from 0 to 1: indicating it becoming assigned at all. [This interpretation arises from statusEquivalents in Scrumbles Objects]

**Comment by fallinbryan** [comment]
xref Epic #153 Implement Item Timline
Will update item status when assigned to user and update itemTimeLine table in database

**Comment by fallinbryan** [comment]
pending pull #222
