### ISSUE TITLE
Sanitize Input before SQL is sent to Database

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#209]
I.e.
"I'm working on this issue tomorrow"
due to the apostrophe the following error will be thrown 

 _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '

**Comment by fallinbryan** [comment]
I will implement sanitation at the Query Object Level.  A decorator func should do the trick.

**Comment by fallinbryan** [comment]
Closure pending approval of pull request #210
