### ISSUE TITLE
Design Flowcharts

### ISSUE THREAD

**Issue by CEN3031-group16** [CEN3031-group16/GroupProject#21]
Design the flowcharts for the application.  Use Visio.  Can be downloaded for free from the Microsoft Imagine university of Florida account.   You must register with you UF email address to be able to download Visio.
Follow the link below to the Microsoft Imagine site:
https://e5.onthehub.com/WebStore/ProductsByMajorVersionList.aspx?cmi_cs=1&cmi_mnuMain=bdba23cf-e05e-e011-971f-0030487d8897&ws=8a314897-739b-e011-969d-0030487d8897&vsro=8

**Comment by fallinbryan** [comment]
this is dead
