### ISSUE TITLE
Inconsistency in Item Priorities & Equivalents

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#216]
priorityEquivalents = {1: "Low Priority", 2: "Medium Priority", 3: "High Priority"}
    statusEquivalents = {0 : 'Not Assigned', 1: 'Assigned', 2: 'In Progress', 3: 'Submitted', 4: 'Complete'}
    statusEquivalentsReverse = {'Not Assigned': 0, 'Assigned': 1, 'In Progress': 2, 'Submitted': 3, 'Complete': 4}

vs
        self.listOfStatuses = {0 : "Not Started", 1 : "In Progress", 2: "Done"}
        self.listOfPriorities = {0 : "Low Priotity", 1 : "Medium Priotity", 2: "High Priotity"}

**Comment by fallinbryan** [comment]
will make everything consistent with:
`statusEquivalents = {0 : 'Not Assigned', 1: 'Assigned', 2: 'In Progress', 3: 'Submitted', 4: 'Complete'}`
`self.listOfPriorities = {0 : "Low Priotity", 1 : "Medium Priotity", 2: "High Priotity"}`

**Comment by fallinbryan** [comment]
complete
