### ISSUE TITLE
Submit For Review -> X on Dialog Bug[s]

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#235]
When you click to submit item for review, then a dialog pops up a to update the item (this should probably be a confirmation dialog).

When you exit out of that the item is submitted for review.

**Comment by fallinbryan** [comment]
should probably give the dialog a better name,  the dialog is to input a link to the code

**Comment by fallinbryan** [comment]
8916d6bdbc81e09bf58364a0c48d0c20ff623972

**Comment by fallinbryan** [comment]
The [X] should not submit the item for review,  the x should cancel the submission.
Does that now.  Also added a cancel button.
Also added yes/no message boxes for all status changes
