### ISSUE TITLE
Implement Help-> User Guide

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#236]
Some one needs to write a guide on how to use Scrumbles

**Comment by fallinbryan** [comment]
Due April 20th
https://ufl.instructure.com/courses/348600/assignments/3499742

**Comment by Stevieberk** [comment]
Available at: https://github.com/CEN3031-group16/GroupProject/wiki/User-Guide

**Comment by Stevieberk** [comment]
Also see README.md
