### ISSUE TITLE
Comment Fast Click Bug Team Manager

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#271]
Clicking between users & items fast in this view causes comments not to show up and eventually become a projection off the main window.

Might be a threading issue, rolling back my bug fixes to see if any of them might have caused it.

**Comment by Kroronos** [comment]
Seems like it existed since colorSchema oldest branch I have on my comp since main.

I have no idea what would cause this.

**Comment by Kroronos** [comment]
![bug271](https://user-images.githubusercontent.com/24195520/38471121-c2bad6d8-3b3a-11e8-8cb8-9edd55445cec.PNG)

**Comment by fallinbryan** [comment]
Unable to duplicate on Lubuntu Linux.  Is this issue only on Windows?

**Comment by fallinbryan** [comment]
nevermind
