### ISSUE TITLE
Add controls etc to MainView

### ISSUE THREAD

**Issue by CEN3031-group16** [CEN3031-group16/GroupProject#28]
Using the wireframe as a template, add the major widgets to the mainView class.   Buttons etc.  can call dummy function that just output text to the python console

**Comment by fallinbryan** [comment]
Changed assignments to reflect pivotal tracker

**Comment by CEN3031-group16** [comment]
Main view implemented by @Kroronos

**Comment by fallinbryan** [comment]
xref Epic #6
