### ISSUE TITLE
Store DB Login Credentials Locally in an encrypted file

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#33]
Currently the login username and password are in the Python Code.  That will pretty much give anyone who looks at the code direct access to the database.

Create a new MySQL User ScrumblesApp
Deploy encrypted login file to team members via email.
Add file to .gitignore so it doesn't get publish

**Comment by fallinbryan** [comment]
The can be implemented in ScrumblesData.DataBaseLoginInfo<br>
`def __init__(self,file):'<br>
`#initialize data from the file`

**Comment by Kroronos** [comment]
Text file is on the dropbox as login.txt, it must be placed in the source folder
Suggested code changes in LoginDBPatch

**Comment by fallinbryan** [comment]
Implemented with merge #59
