### ISSUE TITLE
Refactor getUserID.... to getUser to reflect changes in return Query

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#35]
https://github.com/CEN3031-group16/GroupProject/blob/8146f82d42af33747a9274514c472488969b85b6/source/ScrumblesData.py#L14

**Comment by fallinbryan** [comment]
The function is used other places in the code, so the name has to be changed in more that just the one place

**Comment by Kroronos** [comment]
Refactored
