### ISSUE TITLE
Better SList Sorting

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#64]
Current sorting inside of SList is very primitive, caps > lowercase + no whitespace trimming. Implementing some processing before the sorting occurs should produce results more in line with user expectations.

**Comment by fallinbryan** [comment]
A backlog View/list needs to be sorted by 'Item.itemPriority'

**Comment by Kroronos** [comment]
I'm reserving backlog sorting for sprint 3, would be best to have that done in-line with massive SList refactor.

**Comment by Kroronos** [comment]
Handed off to ryanqfeeney for insane refactor portion
