### ISSUE TITLE
User can Assign Item to a team member

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#77]
SRS states this will be drag and drop
this may l need issue #66 to be implemented
Could be down with a right-click drop down menu

Requires Discussion

**Comment by Stevieberk** [comment]
This should be done by linking the pop up menu from the backlog view to the database right?

**Comment by Stevieberk** [comment]
Implemented in ItemManagerView, still in progress

**Comment by fallinbryan** [comment]
complete
